\set ON_ERROR_STOP on

BEGIN;

\ir 01_schema.sql

CREATE TEMP TABLE stg_dw_ageb ("CVE_AGEB" TEXT, "area_km2" TEXT, "ENTIDAD" TEXT, "MUN" TEXT, "LOC" TEXT, "AGEB" TEXT, "POBTOT" TEXT, "POB0_14" TEXT, "POB15_64" TEXT, "POB65_MAS" TEXT, "PEA" TEXT, "PE_INAC" TEXT, "POCUPADA" TEXT, "PDESOCUP" TEXT, "VIVTOT" TEXT, "TVIVHAB" TEXT, "densidad_pob_km2" TEXT, "tasa_pea" TEXT, "porcentaje_0_14" TEXT, "porcentaje_15_64" TEXT, "porcentaje_65_mas" TEXT, "total_establecimientos" TEXT, "comercio" TEXT, "retail" TEXT, "servicios" TEXT, "otros" TEXT, "actividad_dominante_codigo" TEXT, "actividad_dominante" TEXT, "cantidad_actividad_dominante" TEXT, "densidad_establecimientos_km2" TEXT, "densidad_comercio_km2" TEXT, "densidad_retail_km2" TEXT, "densidad_servicios_km2" TEXT, "establecimientos_por_1000_hab" TEXT, "total_accidentes" TEXT, "total_muertos" TEXT, "total_heridos" TEXT, "accidentes_tipo_1" TEXT, "accidentes_tipo_2" TEXT, "accidentes_tipo_4" TEXT, "accidentes_tipo_5" TEXT, "accidentes_tipo_6" TEXT, "accidentes_tipo_7" TEXT, "accidentes_tipo_8" TEXT, "accidentes_tipo_10" TEXT, "accidentes_tipo_11" TEXT, "densidad_accidentes_km2" TEXT, "accidentes_por_1000_hab" TEXT, "accidentes_por_establecimiento" TEXT) ON COMMIT DROP;

\copy stg_dw_ageb FROM 'data/processed/dw_ageb.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '');

CREATE TEMP TABLE stg_geometry ("CVE_AGEB" TEXT,geometry_wkt TEXT) ON COMMIT DROP;

\copy stg_geometry FROM 'data/processed/ageb_geometry.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '');

CREATE TEMP TABLE stg_temporal ("CVE_AGEB" TEXT,anio TEXT,mes TEXT,periodo_dia TEXT,total_accidentes TEXT,total_muertos TEXT,total_heridos TEXT) ON COMMIT DROP;

\copy stg_temporal FROM 'data/processed/accidentes_tiempo.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '');

INSERT INTO dim_ageb ("CVE_AGEB", "ENTIDAD", "MUN", "LOC", "area_km2", "geometry") SELECT s."CVE_AGEB"::VARCHAR(10), s."ENTIDAD"::INTEGER, s."MUN"::INTEGER, s."LOC"::INTEGER, s."area_km2"::DOUBLE PRECISION, ST_Multi(ST_GeomFromText(g.geometry_wkt,4326)) FROM stg_dw_ageb s JOIN stg_geometry g USING ("CVE_AGEB") ON CONFLICT ("CVE_AGEB") DO UPDATE SET "ENTIDAD"=EXCLUDED."ENTIDAD", "MUN"=EXCLUDED."MUN", "LOC"=EXCLUDED."LOC", "area_km2"=EXCLUDED."area_km2", "geometry"=EXCLUDED."geometry";

INSERT INTO fact_demografia ("CVE_AGEB", "POBTOT", "POB0_14", "POB15_64", "POB65_MAS", "PEA", "PE_INAC", "POCUPADA", "PDESOCUP", "VIVTOT", "TVIVHAB", "densidad_pob_km2", "tasa_pea", "porcentaje_0_14", "porcentaje_15_64", "porcentaje_65_mas") SELECT s."CVE_AGEB"::VARCHAR(10), s."POBTOT"::DOUBLE PRECISION, s."POB0_14"::DOUBLE PRECISION, s."POB15_64"::DOUBLE PRECISION, s."POB65_MAS"::DOUBLE PRECISION, s."PEA"::DOUBLE PRECISION, s."PE_INAC"::DOUBLE PRECISION, s."POCUPADA"::DOUBLE PRECISION, s."PDESOCUP"::DOUBLE PRECISION, s."VIVTOT"::DOUBLE PRECISION, s."TVIVHAB"::DOUBLE PRECISION, s."densidad_pob_km2"::DOUBLE PRECISION, s."tasa_pea"::DOUBLE PRECISION, s."porcentaje_0_14"::DOUBLE PRECISION, s."porcentaje_15_64"::DOUBLE PRECISION, s."porcentaje_65_mas"::DOUBLE PRECISION FROM stg_dw_ageb s ON CONFLICT ("CVE_AGEB") DO UPDATE SET "POBTOT"=EXCLUDED."POBTOT", "POB0_14"=EXCLUDED."POB0_14", "POB15_64"=EXCLUDED."POB15_64", "POB65_MAS"=EXCLUDED."POB65_MAS", "PEA"=EXCLUDED."PEA", "PE_INAC"=EXCLUDED."PE_INAC", "POCUPADA"=EXCLUDED."POCUPADA", "PDESOCUP"=EXCLUDED."PDESOCUP", "VIVTOT"=EXCLUDED."VIVTOT", "TVIVHAB"=EXCLUDED."TVIVHAB", "densidad_pob_km2"=EXCLUDED."densidad_pob_km2", "tasa_pea"=EXCLUDED."tasa_pea", "porcentaje_0_14"=EXCLUDED."porcentaje_0_14", "porcentaje_15_64"=EXCLUDED."porcentaje_15_64", "porcentaje_65_mas"=EXCLUDED."porcentaje_65_mas";

INSERT INTO fact_economia ("CVE_AGEB", "total_establecimientos", "comercio", "retail", "servicios", "otros", "densidad_establecimientos_km2", "densidad_comercio_km2", "densidad_retail_km2", "densidad_servicios_km2", "establecimientos_por_1000_hab", "actividad_dominante_codigo", "actividad_dominante", "cantidad_actividad_dominante") SELECT s."CVE_AGEB"::VARCHAR(10), s."total_establecimientos"::DOUBLE PRECISION, s."comercio"::DOUBLE PRECISION, s."retail"::DOUBLE PRECISION, s."servicios"::DOUBLE PRECISION, s."otros"::DOUBLE PRECISION, s."densidad_establecimientos_km2"::DOUBLE PRECISION, s."densidad_comercio_km2"::DOUBLE PRECISION, s."densidad_retail_km2"::DOUBLE PRECISION, s."densidad_servicios_km2"::DOUBLE PRECISION, s."establecimientos_por_1000_hab"::DOUBLE PRECISION, s."actividad_dominante_codigo"::VARCHAR(10), s."actividad_dominante"::VARCHAR(255), s."cantidad_actividad_dominante"::DOUBLE PRECISION FROM stg_dw_ageb s ON CONFLICT ("CVE_AGEB") DO UPDATE SET "total_establecimientos"=EXCLUDED."total_establecimientos", "comercio"=EXCLUDED."comercio", "retail"=EXCLUDED."retail", "servicios"=EXCLUDED."servicios", "otros"=EXCLUDED."otros", "densidad_establecimientos_km2"=EXCLUDED."densidad_establecimientos_km2", "densidad_comercio_km2"=EXCLUDED."densidad_comercio_km2", "densidad_retail_km2"=EXCLUDED."densidad_retail_km2", "densidad_servicios_km2"=EXCLUDED."densidad_servicios_km2", "establecimientos_por_1000_hab"=EXCLUDED."establecimientos_por_1000_hab", "actividad_dominante_codigo"=EXCLUDED."actividad_dominante_codigo", "actividad_dominante"=EXCLUDED."actividad_dominante", "cantidad_actividad_dominante"=EXCLUDED."cantidad_actividad_dominante";

INSERT INTO fact_accidentes ("CVE_AGEB", "total_accidentes", "total_muertos", "total_heridos", "accidentes_tipo_1", "accidentes_tipo_2", "accidentes_tipo_4", "accidentes_tipo_5", "accidentes_tipo_6", "accidentes_tipo_7", "accidentes_tipo_8", "accidentes_tipo_10", "accidentes_tipo_11", "densidad_accidentes_km2", "accidentes_por_1000_hab", "accidentes_por_establecimiento") SELECT s."CVE_AGEB"::VARCHAR(10), s."total_accidentes"::DOUBLE PRECISION, s."total_muertos"::DOUBLE PRECISION, s."total_heridos"::DOUBLE PRECISION, s."accidentes_tipo_1"::DOUBLE PRECISION, s."accidentes_tipo_2"::DOUBLE PRECISION, s."accidentes_tipo_4"::DOUBLE PRECISION, s."accidentes_tipo_5"::DOUBLE PRECISION, s."accidentes_tipo_6"::DOUBLE PRECISION, s."accidentes_tipo_7"::DOUBLE PRECISION, s."accidentes_tipo_8"::DOUBLE PRECISION, s."accidentes_tipo_10"::DOUBLE PRECISION, s."accidentes_tipo_11"::DOUBLE PRECISION, s."densidad_accidentes_km2"::DOUBLE PRECISION, s."accidentes_por_1000_hab"::DOUBLE PRECISION, s."accidentes_por_establecimiento"::DOUBLE PRECISION FROM stg_dw_ageb s ON CONFLICT ("CVE_AGEB") DO UPDATE SET "total_accidentes"=EXCLUDED."total_accidentes", "total_muertos"=EXCLUDED."total_muertos", "total_heridos"=EXCLUDED."total_heridos", "accidentes_tipo_1"=EXCLUDED."accidentes_tipo_1", "accidentes_tipo_2"=EXCLUDED."accidentes_tipo_2", "accidentes_tipo_4"=EXCLUDED."accidentes_tipo_4", "accidentes_tipo_5"=EXCLUDED."accidentes_tipo_5", "accidentes_tipo_6"=EXCLUDED."accidentes_tipo_6", "accidentes_tipo_7"=EXCLUDED."accidentes_tipo_7", "accidentes_tipo_8"=EXCLUDED."accidentes_tipo_8", "accidentes_tipo_10"=EXCLUDED."accidentes_tipo_10", "accidentes_tipo_11"=EXCLUDED."accidentes_tipo_11", "densidad_accidentes_km2"=EXCLUDED."densidad_accidentes_km2", "accidentes_por_1000_hab"=EXCLUDED."accidentes_por_1000_hab", "accidentes_por_establecimiento"=EXCLUDED."accidentes_por_establecimiento";

INSERT INTO fact_accidentes_tiempo ("CVE_AGEB", "ANIO", "MES", "periodo_dia", "total_accidentes", "total_muertos", "total_heridos") SELECT s."CVE_AGEB"::VARCHAR(10), s."ANIO"::INTEGER, s."MES"::INTEGER, s."periodo_dia"::VARCHAR(20), s."total_accidentes"::DOUBLE PRECISION, s."total_muertos"::DOUBLE PRECISION, s."total_heridos"::DOUBLE PRECISION FROM stg_temporal s ON CONFLICT ("CVE_AGEB", "anio", "mes", "periodo_dia") DO UPDATE SET "ANIO"=EXCLUDED."ANIO", "MES"=EXCLUDED."MES", "total_accidentes"=EXCLUDED."total_accidentes", "total_muertos"=EXCLUDED."total_muertos", "total_heridos"=EXCLUDED."total_heridos";

DELETE FROM fact_accidentes_tiempo t WHERE NOT EXISTS (SELECT 1 FROM stg_temporal s WHERE t."CVE_AGEB"=s."CVE_AGEB" AND t.anio=s.anio::integer AND t.mes=s.mes::integer AND t.periodo_dia=s.periodo_dia);

\ir 03_views.sql

\ir 04_validation.sql

COMMIT;
